### ISSUE TITLE
panic: **k size is greater than sequence length (31 vs 29)**

### ISSUE THREAD

**Issue by GomathiNayagam** [will-rowe/groot#48]
Hi, I have been using Groot for about a month now. I am now seeing an error like the one below, which I don't understand. Could you help me?
Also, I know that my sequences contain a little amount of low quality short sequences. Meanwhile i try with the filtered reads. 

goroutine 1191 [running]:
github.com/will-rowe/groot/src/pipeline.(*theBoss).mapReads.func1(0xc04a4f2910, 0xc00335b0a0, 0x0)
	/Users/willrowe/Desktop/groot/src/pipeline/boss.go:165 +0x5f7
created by github.com/will-rowe/groot/src/pipeline.(*theBoss).mapReads
	/Users/willrowe/Desktop/groot/src/pipeline/boss.go:136 +0x304
panic: **k size is greater than sequence length (31 vs 29)**

**Comment by will-rowe** [comment]
Hi @GomathiNayagam 

Thanks for getting in touch and sorry for the slow reply!

This error is saying that you have chosen a k-mer size that is longer than the sequence length. Looks like this is during read mapping so it is one of your input reads. From memory there should have been an error message thrown instead of this panic, I'll look into it.

To fix, either use a smaller kmer size or try filtering your reads first (use trimmomatic or something) and remove the really short ones.
