### ISSUE TITLE
Paired-end reads information

### ISSUE THREAD

**Issue by hkaspersen** [will-rowe/groot#50]
Dear Authors,
Thank you for creating a great tool!
I was wondering a bit about running your tool with paired-end data. I see you mention that the tool does not utilize the paired-end information. Might I ask what the reason for this is?
Also, if I run the tool with both R1 and R2 concatenated, will the read counts be duplicated? 
Lastly, is it enough to only run on the R1 reads?
Thanks in advance!

**Comment by Leorio183** [comment]
Hello hkaspersen, have you solved this problem? I came across the same issue. How did you do?

Sincerely thanks
Liu Hou

**Comment by will-rowe** [comment]
Sorry for the delay answering. You can provide a concatenated file of both R1 and R2 reads but GROOT won't use the pairing information - this could be a feature but I elected not to handle them as 1 read may be in a resistance gene graph and the other located outside of it. I instead would use GROOT and pair with some sort of localised assembly afterwards, such as metacherchant (see my DRAX pipeline). In answer to your other questions,  it won't double count R1/R2 reads, it just views them as a single data set. Definitely run both R1 and R2 otherwise you are just using half of your data.
