### ISSUE TITLE
Could not unpack the tarball after downloading the arg-annot database

### ISSUE THREAD

**Issue by ropolomx** [will-rowe/groot#8]
Hi. Thanks for the great work with `groot`!  Also, thanks so much for the detailed and comprehensive documentation. Very much appreciated!

I am using version 0.7 that I installed with `conda` from the `bioconda` channel, and I run it in a `conda` environment that I created for it. I am running into the following issue when I want to use the `get` command. It is not a big deal since the arg-annot database is downloaded and I can unpack the tarball manually, but I just thought I would let you know about this. Thank you!

```
downloading the pre-clustered arg-annot database...
unpacking...
could not unpack the tarball
arg-annot.90/: illegal file path
```

**Comment by will-rowe** [comment]
Thanks for the feedback. I've not had that before, it works on my test systems (OSX and Debian). Could it be something to do with file permissions where you are trying to save? Please give me the command you are using and let me know the system you are using and I will try and get to the bottom of it. Thanks!

**Comment by ropolomx** [comment]
Hi Will. This was on a Linux Mint 17.3 system, and I was using the following command: `groot -d arg-annot`, but I have observed the same message after using other commands such as `groot get -d card -i 90` or `groot get -d resfinder -i 90 -o .` 
The downloaded tarball has the following permissions: `-rw-r--r--`

**Comment by will-rowe** [comment]
Thanks for bringing this to my attention - it turns out that it was something I had spotted a while ago, but I forgot to make a release and update the bioconda recipe.... An update to the TAR package (mholt/archiver library) meant that some systems were throwing an error when the groot databases were being unpacked to the current directory. I fixed this in fa78065c4790fd59cf9f9807a391a8fda6f4c88c but have now just pushed a new release af4041817e3634d9fae07b163ff617f645648404 that is used in the new bioconda recipe (v0.7.1). Please try updating your conda install of groot and try running `groot get` again. It should be fixed now!

Will

**Comment by will-rowe** [comment]
Re. my earlier comment about never having had this issue before -- I should add that I have a 6month old and a toddler, which may account for why I couldn't remember coming across and fixing this exact issue myself a few months back! Thanks again for letting me know about this, I hope you are enjoying using groot!

**Comment by ropolomx** [comment]
Hey Will. Thank you very much for this. And thank you very much for making `groot` so awesome! I am really enjoying using it, and I really appreciate the excellent documentation and tutorials! All the best.
